version: 2
jobs:
  build:
    working_directory: ~/shipit
    machine: true
    steps:
       - checkout

       # Install credstash
       - restore_cache:
           keys:
             - "{{ .Environment.CIRCLE_PROJECT_REPONAME }}-credstash"
       - run: pip install credstash
       - save_cache:
           key: "{{ .Environment.CIRCLE_PROJECT_REPONAME }}-credstash"
           paths:
             - /home/circleci/.cache/pip

       - restore_cache:
           keys:
             - "{{ .Environment.CIRCLE_PROJECT_REPONAME }}-{{ .Branch }}"
             - "{{ .Environment.CIRCLE_PROJECT_REPONAME }}-master"
       - run: sbt test:compile
       - save_cache:
           key: "{{ .Environment.CIRCLE_PROJECT_REPONAME }}-{{ .Branch }}"
           paths:
             - /home/circleci/.ivy2
             - /home/circleci/.sbt
             - /home/circleci/.coursier
             - project/target/resolution-cache
             - target/resolution-cache
       - run: sbt test docker:publishLocal
       - deploy:
           name: Deploy if master branch
           command: |
             if [ "${CIRCLE_BRANCH}" == "master" -a "${CIRCLE_PROJECT_USERNAME}" == "ovotech" ]; then
               git clone git@github.com:ovotech/comms-ci-scripts
               comms-ci-scripts/publish_docker_image.sh
               comms-ci-scripts/deploy_to_ecs.sh -s shipit PRD aws/container-definition.json
               comms-ci-scripts/comment_on_last_merged_pr.sh
             fi
