version: 2

jobs:
  build:
    working_directory: ~/shipit
    docker:
      - image: circleci/openjdk:11.0.5-jdk-stretch
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install AWS CLI
          command: scripts/ci/install-aws-cli.sh
      - restore_cache:
          keys:
            - '{{ .Environment.CIRCLE_PROJECT_REPONAME }}-dependencies-{{ checksum "build.sbt" }}'
      - run: sbt test:compile
      - save_cache:
          key: '{{ .Environment.CIRCLE_PROJECT_REPONAME }}-dependencies-{{ checksum "build.sbt" }}'
          paths:
            - /home/circleci/.ivy2
            - /home/circleci/.sbt
            - /home/circleci/.coursier
            - project/target/resolution-cache
            - target/resolution-cache
      - run: sbt test docker:publishLocal
      - run:
          name: Publish docker image if master branch
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" -a "${CIRCLE_PROJECT_USERNAME}" == "ovotech" ]; then
              scripts/ci/publish-docker-image.sh
            else
              echo "Not publishing Docker image"
            fi

  deploy:
    working_directory: ~/shipit
    docker:
      - image: circleci/openjdk:11.0.5-jdk-stretch
    steps:
      - checkout
      - run:
          name: Install AWS CLI
          command: scripts/ci/install-aws-cli.sh
      - run:
          name: Deploy to ECS
          command: scripts/ci/deploy-to-ecs.sh
      - run:
          name: Notify Shipit
          command: |
            curl https://shipit.ovotech.org.uk/deployments?apikey=$SHIPIT_API_KEY \
              -d "team=eng-services" \
              -d "service=shipit" \
              -d "buildId=$CIRCLE_BUILD_NUM" \
              -d "links[0].title=CircleCI build" \
              -d "links[0].url=$CIRCLE_BUILD_URL"

workflows:
  version: 2
  default:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - master
